version: "3.8"

services:
  sla_report:
    build: .
    container_name: sla_report
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - ./sla_reporting:/root/sla_reporting
    command: ["python", "python/main.py"]

